# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

logging:
  level:
    ROOT: INFO
    hr.ecc.corepoc.demo: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger
  jackson:
    serialization:
      indent-output: true

server:
  port: 8080

# ===================================================================
# Application specific properties
# ===================================================================
