version: '3'
services:
  core-poc-demo-java:
    image: ecc/core-demo-java:0.0.1
    environment:
      _JAVA_OPTIONS: "-Xmx512m -Xms256m"
      SPRING_PROFILES_ACTIVE: "dev,swagger"
      SERVER_SERVLET_CONTEXT_PATH: "/"
    ports:
      - 8080:8080
